### ISSUE TITLE
Futures timed out after 1 minute

### ISSUE THREAD

**Issue by johdah** [KarelCemus/play-redis#113]
When I run a small benchmark test on an application that uses play-redis i get timeouts. With the same setup but the old play-redis plugin from Typesafe there is no problem. So the Redis server should be fine.

The benchmark is running at 13 events/sec and the mean max time is 300 ms and the mean 30 ms so it's not high load on Redis.

I can't see any other warnings or errors from play-redis, and it shouldn't be more than a millisecond to get the response from Redis.

```
[error] c.Application/Feedbacks - Futures timed out after [1 minute]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
	at scala.concurrent.Await$.result(package.scala:190)
	at play.api.cache.redis.impl.Builders$SynchronousBuilder$$anonfun$toResult$4.apply(Builders.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at play.api.cache.redis.impl.Builders$SynchronousBuilder$.toResult(Builders.scala:48)
	at play.api.cache.redis.impl.dsl$RecoveryFuture$.recoverWithDefault$extension(dsl.scala:25)
	at play.api.cache.redis.impl.RedisMapImpl.add(RedisMapImpl.scala:18)
	at dao.RedisDAOImpl.hset(RedisDAOImpl.scala:264)
	at dao.FeedbackDAO.updateLatestFeedbackTime(FeedbackDAO.java:153)
...
```

hset is just a small scala wrapper since I can't use the play.api.cache.redis.CacheApi with Java.

```scala
def hset(key: String, field: String, value: String): Boolean = {
    cache.map[ String ]( key ).add( field, value )
    true
}
```

application.conf
```
play {
  cache {
    redis {
      timeout = 1m
    }
  }
}

scredis.io {
  connect-timeout = 3s
  receive-timeout = 1s
}
```

**Comment by KarelCemus** [comment]
Hi, is it a possible duplicate of #85? 

I am quite sure the timeout is caused by the `SyncApi`, since `AsyncApi` does not use the timeout at all. The question is why.

Could you post here the whole benchmark so I could review and reproduce it? What operations are you calling? Only `hset`?

**Comment by johdah** [comment]
It might be a duplicate, but I thought his problem was solved with an update.

We benchmark our own service so it's not possible to share it. We mostly use hset and hget but it's only in our hset method we get the timeout. I'm not sure that means that hget is ok, but most of the reading is done in another application that uses the old redis plugin.

**Comment by KarelCemus** [comment]
If you use only map-related operations, then the issues are probably not related.

Well, it is difficult to trace the issue when I cannot reproduce it.

**Comment by johdah** [comment]
When I have some time I could try to reproduce it in some Play example project.

I'm not really sure how it works with execution context. Is the plugin switching context? Because if so it would mean that the plugin had to wait for a thread to become available and could timeout during that time? In that case this is maybe just a symptom and not the cause.

Because I guess that the old play plugin didn't and that could explain why that one worked.

**Comment by KarelCemus** [comment]
It would be great if you delivered an example.

>  Is the plugin switching context? 

Sure it does, many times. It is fully async under the hood, so it releases the thread many times. If something else takes it and won't release it and the thread pool gets empty that would be the cause.

**Comment by KarelCemus** [comment]
Well, if it is the cause than what about custom thread pool? You can try defining a custom Akka dispatcher and pool. Look [here](https://github.com/KarelCemus/play-redis/blob/master/src/main/resources/reference.conf#L24)

**Comment by johdah** [comment]
I have tried to use a custom thread pool but it doesn't look like it's used.

```
play.cache.redis.dispatcher: contexts.redis

contexts {
  redis {
    executor = "thread-pool-executor"
    throughput = 1
    thread-pool-executor {
      fixed-pool-size = 10
    }
  }
}
```

**Comment by KarelCemus** [comment]
How could you tell? I conducted couple tests and the context use seems alright.

**Comment by johdah** [comment]
I don't know how to tell. But I can't understand how I can still get the timeout this early in the test if it uses a custom context. Redis should be very fast (<10 ms) and it still get's a 1 minute timeout.

I still think the cause was that there was no threads available in the first place. Is the custom dispatcher always used or just when waiting for the response from Redis?

**Comment by KarelCemus** [comment]
Well, it should be always but not sure what about `scredis`. Might be worth checking.

**Comment by KarelCemus** [comment]
I am worried `scredis` uses default context [in multiple places](https://github.com/scredis/scredis/search?utf8=%E2%9C%93&q=global&type=). Not sure what can be done about it. However, can you use more recent version of play-redis? It uses different connector as there were several issues with scredis.

**Comment by KarelCemus** [comment]
I checked, rediscala used since version 1.5.0 uses custom context.

**Comment by johdah** [comment]
Ah, I use 1.5.1 but didn't now that Scredis was replaced. I got the scredis config from the other timeout issue.

**Comment by KarelCemus** [comment]
I don't think we can narrow the issue down without having a "working" example. I use play-redis in several production applications with higher traffic than 30 events per sec and never had an issue. So I believe the issue is within the benchmark itself but without seeing the code I cannot be sure, sorry.

It would help if you deliver the example when you can.

**Comment by johdah** [comment]
Yes, I have this far failed to reproduce it in a separate project so I'm pretty sure that it's the theory I had before. That the DB takes so much time and that it affects play-redis more since it drops the threads more and is used a lot. I think that the stack trace changed a bit when I added the custom dispatcher so I will look into it more tomorrow.

**Comment by johdah** [comment]
I thought that I had said this already. But I rewrote all DB-related code so that it has it's own execution context and that solved the problem. Now I don't have those problems anymore.

**Comment by KarelCemus** [comment]
Thanks for the update. So this issue is not related to play-redis? Can I safely close it?

**Comment by johdah** [comment]
It's related in the sense that play-redis drops threads (nothing wrong in that) a lot and that causes problem when you have a lot of blocking code in the project. But, since best practices say that blocking code should be in a separate execution context, I think this can be closed.

**Comment by KarelCemus** [comment]
Well, there is a lot of IO operations, I think it is correct that it drops threads a lot. It saves resources. 

Thanks for the update.

**Comment by simonitstrategen** [comment]
Hey guys,

I have almost the same problem after upgrading from play 2.5 (with jedis connector) to play 2.6 (and play-redis). 

I have a scheduler to reindex all user in the redis. So the scheduler spawns an actor for each user, the actor access the cache and wants to set a simple string for each user. 
Unfortunately I get an TimeoutException (ater reindex ~100 of 2000 User):

Does anyone have an idea?

Thanks and best regards,
Simon
`java.util.concurrent.TimeoutException: Futures timed out after [1000000000 nanoseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at scala.concurrent.Await$.result(package.scala:190)
	at play.api.cache.redis.impl.Builders$SynchronousBuilder$$anonfun$toResult$4.apply(Builders.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at play.api.cache.redis.impl.Builders$SynchronousBuilder$.toResult(Builders.scala:48)
	at play.api.cache.redis.impl.dsl$RecoveryUnitFuture$.recoverWithDone$extension(dsl.scala:39)
	at play.api.cache.redis.impl.RedisCache.set(RedisCache.scala:24)`

**Comment by KarelCemus** [comment]
Hi @simonitstrategen, it is hard to say without seeing the actual code. The easiest solution is not to use synchronous API, though. What methods on the cache API do you call? Could you provide a full stacktrace? It does not seem likely to timeout only inside `set` method.

**Comment by KarelCemus** [comment]
Actually, browsing this thread, if there is a lot of concurrent threads and you use blocking API, then it is probably that all threads get blocked and you run out of threads thus the timeout. This seems to be very probably the cause of your timeout.

Solutions:
- use custom execution context
- use async api

**Comment by simonitstrategen** [comment]
Hy @KarelCemus, thanks for the fast reply!

We use directly your redis api classes because the CacheApi from play only covers 4 or 5 methods to interact with the cache. But we need the whole Hash and List functionality:

` @Inject
    public Cache(play.api.cache.redis.CacheApi cache) {
        this.cache = cache;
        this.tag = scala.reflect.ClassTag$.MODULE$.apply(String.class);
    }

   public void set(String key, String value)
    {
        cache.set(key, value, scala.concurrent.duration.Duration.Inf());
    }`


To avoid thread-problems we are using akka to spawn the actors:

`    for (User user : active) {
                        ActorRef userActor = system.actorOf(Props.create(DependencyInjector.class, injector, UpdateRedisActor.class));
                        userActor.tell(new UpdateRedisActor.Index(user.getId()), null);
                    }`



Full Stack-Trace:

`2017-10-12 09:35:11,085 [error] [akka.actor.OneForOneStrategy] - Futures timed out after [1000000000 nanoseconds]
java.util.concurrent.TimeoutException: Futures timed out after [1000000000 nanoseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at scala.concurrent.Await$.result(package.scala:190)
	at play.api.cache.redis.impl.Builders$SynchronousBuilder$$anonfun$toResult$4.apply(Builders.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at play.api.cache.redis.impl.Builders$SynchronousBuilder$.toResult(Builders.scala:48)
	at play.api.cache.redis.impl.dsl$RecoveryUnitFuture$.recoverWithDone$extension(dsl.scala:39)
	at play.api.cache.redis.impl.RedisCache.set(RedisCache.scala:24)
	at utils.cache.Cache.set(Cache.java:90)
	at actors.user.UpdateRedisActor.index(UpdateRedisActor.java:59)
	at actors.user.UpdateRedisActor.onReceive(UpdateRedisActor.java:35)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:166)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:514)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:96)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
`


Part of actor which is using the cache (in this case our own wrapper. See above):

`
            String id = String.valueOf(user.getId());
            cache.set(cacheKeyHandler.getLoginKey(user.getUsername()), id);
`

Best regards 
Simon

**Comment by KarelCemus** [comment]
Have you already considered my note regarding the running out of the threads? It still seems as the most likely cause.

**Comment by simonitstrategen** [comment]
Yes I see. Mhm. I removed the akka-actor-spawning part and access the cache directly. That is working! Thanks for the hint!

Strange is that this was running with jedisPool without any problems. Mhm maybe the timeout was higher in jedisPool or something changed in the akka handling in play 2.6.

Thanks,
Simon

**Comment by KarelCemus** [comment]
The timeout is not the issue, it is the symptom. When you are run out of threads, you have basically a deadlock - the timeout is the solution as it frees some blocked threads and resumes the application.

I am not sure, never used it but I think jedis is synchronous under the hood, i.e., it does not release a thread and thus does not have to acquire it again (which could be unavailable as was in your case).
