### ISSUE TITLE
Redis connection problem

### ISSUE THREAD

**Issue by mmolinos** [KarelCemus/play-redis#134]
### Reporting a bug
1. Version of play-redis **1.6.1**
1. Version of Play **2.6.x**
1. Describe the actual behavior, follow the same scenario
Our version of redis is `docker run -d --name redis-cache -p 6379:6379 redis:4-alpine`
We have configured the play-redis like you said on the wiki. After this, we try to do a `cache.get()` and the system is blocked for 1 min more or less, after this we receive this log:
**Command GET for key 'classTag::access_token' failed.**
 _stack_trace_:
`redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n`

**Comment by KarelCemus** [comment]
Hi, first of all, I have to apologize. I updated the documentation to version 2.0 but I'm not able to finish the release of the version 2.0 and there are some significant changes in the configuration. So, first of all, please check your configuration according to the [documentation of version 1.6.1](https://github.com/KarelCemus/play-redis/tree/1.6.1), which is still in README. Wiki applies since unreleased 2.0.

Next, if the configuration is correct, according to the exception, you use Java API to get the value. As this API does not provide a classtag, while Scala version does, play-redis workarounds this by storing a classtag to. So when you want to get the value by Java API, you have to store it by Java API too.

Could you confirm both of these conditions (correct configuration - you can paste it here - and the use) are satisfied?

**Comment by mmolinos** [comment]
Hi Karel,

we have the same problem yet. Here is our configuration:
```
akka {
	actor {
		serializers {
			kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
		}
		serialization-bindings {
			"com.telefonica.baikal.play.auth.Token" = kryo
		}
	}
}
play {
	modules {
		enabled += "play.api.cache.redis.RedisCacheModule"
	}
	cache {
		redis {
			host = ${?REDIS_HOST}
			port = ${?REDIS_PORT}
		}
	}
}
```

My code for get and set the values is this:

```
import play.cache.AsyncCacheApi;

...
	@Inject
	public Example(AsyncCacheApi cache) {
		this.cache = cache;
	}

	public CompletionStage<String> getAccessToken(Token token) {
  		return this.cache.set("KEY_CACHE_EXAMPLE", token, 150);
	}
	
	public CompletionStage<Token> getCachedToken() {
		return this.cache.get("KEY_CACHE_EXAMPLE");
	}
...
```

**Comment by KarelCemus** [comment]
The configuration seems to be correct. Could you check the logs? When the application starts, the redis connects to the instance. When it fails, there should be some warnings or errors, otherwise there are info logs.

**Comment by mmolinos** [comment]
Hi Karel,

I attach here my log:

```
{INFO:"Redis cache actor started. It is connected to localhost:6379?database=1"}
{INFO:"Application started (Dev)"}
{WARN:"ConnectionClosed ErrorClosed(Conexi\u00F3n reinicializada por la m\u00E1quina remota)"}
{ERROR:"Command GET for key 'classTag::access_token' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"}
{ERROR:"Command GET for key 'classTag::access_token' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"}
{ERROR:"Command SETEX for key 'access_token' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"}
{ERROR:"Command SETEX for key 'access_token' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"}
{ERROR:"Command SETEX for key 'classTag::access_token' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"}
{ERROR:"Command SETEX for key 'classTag::access_token' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)\n\tat redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:20)\n\tat redis.actors.RedisReplyDecoder$$anonfun$postStop$1.apply(RedisReplyDecoder.scala:19)\n\tat scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)\n\tat scala.collection.mutable.MutableList.foreach(MutableList.scala:30)\n\tat redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)\n\tat akka.actor.Actor$class.aroundPostStop(Actor.scala:527)\n\tat redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)\n\tat akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)\n\tat akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)\n\tat akka.actor.ActorCell.terminate(ActorCell.scala:370)\n\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)\n\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)\n\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"}
```

**Comment by KarelCemus** [comment]
```
{WARN:"ConnectionClosed ErrorClosed(Conexi\u00F3n reinicializada por la m\u00E1quina remota)"}
```

This one is stranger. It is obviously raised from [here](https://github.com/etaty/rediscala/blob/master/src/main/scala/redis/actors/RedisWorkerIO.scala#L108) in rediscala, which the underlying connector.

Are you sure the instance is running at localhost:6379 and is working? To be honest the first info log is submitted without any checks it is actually running, it relies on the underlying connector to emit errors if there are some.

However, this looks like the library tries to connect to redis running at localhost:6379, which fails. Isn't there, e.g., a password or something?

**Comment by mmolinos** [comment]
In the first line you can see how the app was connected to Redis: `{INFO:"Redis cache actor started. It is connected to localhost:6379?database=1"}`
I did a telnet to this port and host from my computer and it works.

**Comment by KarelCemus** [comment]
That line is what I was talking about:

> To be honest the first info log is submitted without any checks it is actually running, it relies on the underlying connector to emit errors if there are some.

So when it says "connected" it actually means "connecting". Maybe I should correct the message. However, it does not actually mean it is successfully connected

**Comment by KarelCemus** [comment]
and what about `redis-cli` command running at that localhost, works?

**Comment by mmolinos** [comment]
Yes, I can enter with a redis-cli in the tool and after this, I can monitor all info

**Comment by KarelCemus** [comment]
This is though to say why the connection fails, when we cannot reproduce it. There are other users using play-redis with docker and it works. I believe there are some local conditions causing it. Maybe raise the question in `rediscala` issue tracking, this seems to be more related to the connector itself.

**Comment by KarelCemus** [comment]
`Conexi\u00F3n reinicializada por la m\u00E1quina remota` Could you translate it into english? It's (don't know why) localized.

**Comment by mmolinos** [comment]
Connection was reset for the remotely computer

**Comment by KarelCemus** [comment]
I'm sorry, really don't know how to help when I cannot reproduce it. Possibly enable trace logging for rediscala and check the logs of that and of the redis server itself, there might be some hint there.

**Comment by mmolinos** [comment]
Ok, thanks anyway

**Comment by mmolinos** [comment]
Hi Karel,
sorry for the inconveniences. You can reproduce the error here. In this repository, you can download an example app with the issue and in the `README.md` you can see how to deploy this app.
[https://github.com/mmolinos/examplePlayRedisPlayConnector](https://github.com/mmolinos/examplePlayRedisPlayConnector)
Thanks.

**Comment by KarelCemus** [comment]
I tested your example. There is an issue in your HomeController at [line 40]. The second attribute should be a charset but you put there a word "cache", which is invalid charset. See the [signature](https://github.com/playframework/playframework/blob/12700b3b6d7aca035a6db46188a05b3262e19d4b/framework/src/play/src/main/java/play/mvc/Results.java#L275). When I fixed this, it worked as expected.

**Comment by mmolinos** [comment]
Hi Karel,

I update my code with this error that you comment and I have the same error. Can you reproduce it with my new code? https://github.com/mmolinos/examplePlayRedisPlayConnector
```
[info] play.api.Play - Application started (Dev)
[warn] r.a.RedisClientActor - ConnectionClosed ErrorClosed(Reset connection by the remote machine)
[error] p.a.cache.redis - Command GET for key 'classTag::CACHE_KEY' failed.
redis.actors.InvalidRedisReply$: Could not decode the redis reply (Connection closed)
	at redis.actors.InvalidRedisReply$.<clinit>(RedisReplyDecoder.scala)
	at redis.actors.RedisReplyDecoder.$anonfun$postStop$1(RedisReplyDecoder.scala:20)
	at scala.collection.LinearSeqOptimized.foreach(LinearSeqOptimized.scala:71)
	at scala.collection.LinearSeqOptimized.foreach$(LinearSeqOptimized.scala:68)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
	at redis.actors.RedisReplyDecoder.postStop(RedisReplyDecoder.scala:19)
	at akka.actor.Actor.aroundPostStop(Actor.scala:536)
	at akka.actor.Actor.aroundPostStop$(Actor.scala:536)
	at redis.actors.RedisReplyDecoder.aroundPostStop(RedisReplyDecoder.scala:11)
	at akka.actor.dungeon.FaultHandling.finishTerminate(FaultHandling.scala:210)
```

**Comment by mmolinos** [comment]
I discovered that is problem with my local configuration of docker
thanks for all help
