### ISSUE TITLE
Cluster mode does not seem to work with play 2.6.

### ISSUE THREAD

**Issue by pandian-egnaroinc** [KarelCemus/play-redis#150]
Are you filing an issue? Please follow these checklists and provide us all the possible information to speed up the process.

1. Version of play-redis
2.0.2

1. Version of Scala
Java 1.8.

1. Version of Play
2.6
akka-actor version 2.5.8.

1. Describe the environment if applies (usually in cloud etc.)
Consistent with even local redis cluster.

1. Describe the expected behavior
Should connect to cache endpoint.

1. Describe the actual behavior, follow the same scenario
RedisScala expects akka-actor version 2.4.2 which is incompatible with play 2.6.

```
[warn] 	* com.typesafe.akka:akka-actor_2.12:2.5.8 is selected over {2.4.12, 2.4.20}
[warn] 	    +- com.typesafe.akka:akka-slf4j_2.12:2.5.8 ()         (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-stream_2.12:2.5.8 ()        (depends on 2.5.8)
[warn] 	    +- com.typesafe.play:play_2.12:2.6.11                 (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-parsing_2.12:10.0.11 ()     (depends on 2.4.20)
[warn] 	    +- com.github.etaty:rediscala_2.12:1.8.0 ()           (depends on 2.4.12)
```

Throws below exception:

```
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] p.a.cache.redis - Redis cache actor started. It is connected to localhost:6379
[info] p.a.cache.redis - Redis cluster cache actor started. It is connected to  localhost:30001
[error] a.a.OneForOneStrategy - null
java.lang.NullPointerException: null
	at redis.RedisCluster.$anonfun$onConnectStatus$1(RedisCluster.scala:46)
	at redis.RedisCluster.$anonfun$onConnectStatus$1$adapted(RedisCluster.scala:41)
	at redis.actors.RedisWorkerIO.onConnected(RedisWorkerIO.scala:70)
	at redis.actors.RedisWorkerIO$$anonfun$connecting$1.applyOrElse(RedisWorkerIO.scala:57)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at redis.actors.RedisWorkerIO.aroundReceive(RedisWorkerIO.scala:15)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):
[info] play.api.Play - Application started (Dev)
```

1. Provide instructions to reproduce the issue
Install local redis cluster.
Configure as below:

```
play.cache.redis {
  source: standalone

  instances {
    play {
      # source property fallbacks to the value under play.cache.redis
      host:       localhost
      port:       6379
    }
    ITS {
      source: cluster
      cluster: [
        { host: localhost, port: 30001 }
      ]
    }
  }
}
```

Standalone instance connects fine but cluster instance throws exception.

**Comment by pandian-egnaroinc** [comment]
I have written a custom provider in java with the same issue. Can share code if needed.
