### ISSUE TITLE
play.api.cache.redis - Deserialization failed for key

### ISSUE THREAD

**Issue by cgq6181** [KarelCemus/play-redis#235]
Are you filing an issue? Please follow these checklists and provide us all the possible information to speed up the process.

### Reporting a bug?
1. Version of play-redis  2.6.1
1. Version of Scala.    2.12.10
1. Version of Play.   2.7.4
1. Describe the environment if applies (usually in cloud etc.)
1. Describe the expected behavior
1. Describe the actual behavior, follow the same scenario
1. Provide instructions to reproduce the issue

### Proposing a feature?

1. Describe the new feature
1. Propose the use if applies, i.e., the public API and how to integrate with the application

When I try to get the value from Redis cache got an exception, I don't understand why this is causing

Code

`package controllers

import javax.inject.Inject
import play.api.cache.redis.CacheAsyncApi
import play.api.mvc.{AbstractController, ControllerComponents}
import javax.inject._
import play.cache.NamedCache

import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global

class FacetsController @Inject()(@NamedCache("localCache") localCache: CacheAsyncApi, controllerComponents:ControllerComponents, facetsResolver: FacetsResolver, serializer: FacetsJsonTransformer) extends AbstractController(controllerComponents) {

  private def message(instance: CacheAsyncApi, name: String ) = instance.getOrElse( "Name") {
    instance.set("Name","Chandrashekhar")
    println(instance.get("Name"))
    "Value not stored in cache"
  }

  private def messageInLocal = message(localCache, "localCache" )

  def index = Action.async {
    messageInLocal.map( msg => Ok(msg))
  }

}
`

Config

`# enable redis cache module
play.modules.enabled += play.api.cache.redis.RedisCacheModule

#play.cache.createBoundCaches = false
play.cache.redis {
    host:       localhost
    # redis server: port
    port:       6379
    # redis server: database number (optional)
    database:  0

    recovery: log-and-default
    bind-default: false
    default-cache: "localCache"
    invocation:   lazy
  }
`

12:07:09.214 [application-akka.actor.default-dispatcher-2] ERROR play.api.cache.redis - Deserialization failed for key 'Name'.
java.lang.IllegalArgumentException: Type Nothing is not supported. You have probably forgot to specify expected data type.
	at play.api.cache.redis.connector.AkkaDecoder.untypedDecode(AkkaSerializer.scala:103)
	at play.api.cache.redis.connector.AkkaDecoder.decode(AkkaSerializer.scala:97)
	at play.api.cache.redis.connector.AkkaSerializerImpl.$anonfun$decode$1(AkkaSerializer.scala:165)
	at scala.util.Try$.apply(Try.scala:213)
	at play.api.cache.redis.connector.AkkaSerializerImpl.decode(AkkaSerializer.scala:165)
	at play.api.cache.redis.connector.RedisConnectorImpl.play$api$cache$redis$connector$RedisConnectorImpl$$decode(RedisConnectorImpl.scala:55)
	at play.api.cache.redis.connector.RedisConnectorImpl$$anonfun$get$1.applyOrElse(RedisConnectorImpl.scala:34)
	at play.api.cache.redis.connector.RedisConnectorImpl$$anonfun$get$1.applyOrElse(RedisConnectorImpl.scala:31)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by KarelCemus** [comment]
you must explicitly provide expected data type here since type inference is not able to infer correct type. So instead of `println(instance.get("Name"))` you must write `println(instance.get[String]("Name"))`

**Comment by cgq6181** [comment]
Thanks, Karel
