### ISSUE TITLE
Redis cluster Connection issue

### ISSUE THREAD

**Issue by cgq6181** [KarelCemus/play-redis#237]
Are you filing an issue? Please follow these checklists and provide us all the possible information to speed up the process.

### Reporting a bug?
1. Version of play-redis. 2.6.1
1. Version of Scala.     2.12.10
1. Version of Play.       2.7.4
1. Describe the environment if applies (usually in cloud etc.) local
1. Describe the expected behavior
1. Describe the actual behavior, follow the same scenario
1. Provide instructions to reproduce the issue

### Proposing a feature?

1. Describe the new feature
1. Propose the use if applies, i.e., the public API and how to integrate with the application

I am not able to connect to my Redis cluster

Configuration which is I used 
`play.cache.redis {
    #enable cluster mode
    source: cluster

    # nodes are defined as a sequence of objects:
    cluster: [
        {
            host: ${REDIS_INSTANCE_1}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
        }
    ]
}`

when I try to connect using cluster it's throwing below exception

19:00:04.723 [application-akka.actor.default-dispatcher-5] ERROR akka.actor.OneForOneStrategy - ByteString(45, 69, 82, 82, 32, 84, 104, 105, 115, 32, 105, 110, 115, 116, 97, 110, 99, 101, 32, 104, 97, 115, 32, 99, 108, 117, 115, 116, 101, 114, 32, 115, 117, 112, 112, 111, 114, 116, 32, 100, 105, 115, 97, 98, 108, 101, 100, 13, 10) (of class akka.util.ByteString$ByteString1)
scala.MatchError: ByteString(45, 69, 82, 82, 32, 84, 104, 105, 115, 32, 105, 110, 115, 116, 97, 110, 99, 101, 32, 104, 97, 115, 32, 99, 108, 117, 115, 116, 101, 114, 32, 115, 117, 112, 112, 111, 114, 116, 32, 100, 105, 115, 97, 98, 108, 101, 100, 13, 10) (of class akka.util.ByteString$ByteString1)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:259)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:257)
	at redis.protocol.RedisProtocolReply$$anonfun$5.applyOrElse(RedisProtocolReply.scala:164)
	at redis.protocol.RedisProtocolReply$$anonfun$5.applyOrElse(RedisProtocolReply.scala:164)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at redis.api.clusters.ClusterSlots$$anonfun$1.applyOrElse(Clusters.scala:67)
	at redis.api.clusters.ClusterSlots$$anonfun$1.applyOrElse(Clusters.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at redis.Operation.decodeRedisReplyThenComplete(Operation.scala:9)
	at redis.actors.RedisReplyDecoder.decodeRedisReply(RedisReplyDecoder.scala:64)
	at redis.actors.RedisReplyDecoder.decodeRepliesRecur(RedisReplyDecoder.scala:50)
	at redis.actors.RedisReplyDecoder.decodeReplies(RedisReplyDecoder.scala:35)
	at redis.actors.RedisReplyDecoder$$anonfun$receive$1.applyOrElse(RedisReplyDecoder.scala:28)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at redis.actors.RedisReplyDecoder.aroundReceive(RedisReplyDecoder.scala:11)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by KarelCemus** [comment]
Hey, are you sure that your local redis instance is started in a cluster mode? therefore it has at least 3 nodes? Otherwise, it is invalid cluster setup

**Comment by KarelCemus** [comment]
Closing for inactivity. If you still see this issue and the suggested solution doesn't help, feel free to reopen this ticket
