### ISSUE TITLE
Excessive logging with akka.pattern.AskTimeoutException

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#46]
When requests to redis timeouts due to, e.g., disconnection, there is unnecessary excessive logging. Such exceptions should be handled with more condensed log messages

```logs
10:40:54 [error] play.api.cache.redis SETEX command failed for key 'mykey'.
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://application/user/$b#1419961090]] after [1000 ms]. Sender[null] sent message of type "brando.Request".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:122)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:322)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:274)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:278)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:230)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by KarelCemus** [comment]
Also related to #44, way to much logs when not connected

**Comment by KarelCemus** [comment]
Designed condensed log versions, see RecoveryPolicy for more details

Reduced logs in tests via policy customization
